/************************
 * Version              Date            Name            Description
 * ===========================================================================================
 * V1.0               26/07/2024        Developer1      Add Method Implementation         
 * 
 * 
 * ************************/


public with sharing class Calculator {
    public Calculator() {

    }

    public integer add(integer a, integer b){
        return a+b;
    }

}